### PR TITLE
Fixed NPE, added some logging for when we encounter an invalid rule name

### PR DESCRIPTION
**Pull request by wheelerlaw**
If there is an invalid rule name passed as a part of the `ruleset` argument, a NPE will be thrown. This fixes it so it fails gracefully, reporting the issue, and moves on to the next rule.

### CODE REVIEW

**Comment by chrismair** [comment]
I agree that the NPE with no useful info needs to be fixed. The other ruleset implementations (Groovy DSL, XML) do not warn+ignore invalid rule names, but do throw an exception that includes the invalid rule name, e.g. “No such rule named [ClassName]”.

I would prefer to have the JSON ruleset behave the same way. So I'd like to change only the two lines starting on line 64, including adding the null-safe operator that you identified:
```
                RuleRegistryHolder.ruleRegistry?.getRuleClass(ruleName)?.name // ex: CatchThrowableRule
        assert ruleClassName, "No such rule named [$ruleName]"
```
and add this test to `JsonReaderRuleSetTest`:
```
    @Test
    void testRuleNameNotFound() {
        final JSON = '''
            {
                "DoesNotExist": {}
            }
            '''
        shouldFailWithMessageContaining('DoesNotExist') { parseJsonRuleSet(JSON) }
    }
```

Is that reasonable?

**Comment by wheelerlaw** [comment]
Very. I will adjust the PR accordingly.

**Comment by chrismair** [comment]
We are planning for the next CodeNarc release within the week or so. Are you still intending on reworking this PR?

**Comment by chrismair** [comment]
I manually made the changes agreed to above.

**Pull request closed without merging**
