### PR TITLE
RuleSets file in JSON format

### PR DESCRIPTION
**Pull request by nvuillam**
Allow to use RuleSets in JSON format

Updated documentation:

## Creating a JSON RuleSet File

You can use ruleset file in JSON format, which will be an JSON object declaring all rules and their properties

Format:

```json
{
    "RuleName1" : { "prop1": "value1", "prop2": "value2"},
    "RuleName2" : { "prop3": "value3"},
    "RuleName3" : { }
}
```

**Note**: `RuleName` can have one of the following formats :

* name (ex: `SpaceAroundMapEntryColon`)
* class (ex: `org.codenarc.rule.formatting.SpaceAroundMapEntryColon` )

**Note**: If rule parameters is an empty object, default CodeNarc rule values will be used

### A Sample JSON RuleSet

Here is an example JSON *RuleSet* file:

```json
{
        "Indentation": { "spacesPerIndentLevel": 4 },
        "SpaceAroundMapEntryColon": { "enabled" : false },
        "ExplicitCallToEqualsMethod": { "priority": 3},
        "Println": { }
}

### CODE REVIEW

**Comment by nvuillam** [comment]
CI success : https://travis-ci.org/github/CodeNarc/CodeNarc/builds/725850077

**Comment by chrismair** [comment]
Nice work!

 - Please remove the support for specifying the ruleset ("theme") prefix for rule names in the JSON ruleset. We are deliberately trying to reduce/minimize the coupling with rulesets, to ease future reorganization. We encourage use of rule name only.

 - The `JsonFileRuleSet`constructor javadoc mentions "XML".

 - Please add tests to `RuleSetUtilTest` for new JSON logic.

Thanks.

**Comment by nvuillam** [comment]
@chrismair Updates processed, CI passing :) https://travis-ci.org/github/CodeNarc/CodeNarc/builds/726628339

**Comment by chrismair** [comment]
Looks good! Thanks for the contribution.

**Pull request merged**
