### PR TITLE
Grails rule which guarantees presence of max size constraint on String properites

### PR DESCRIPTION
**Pull request by musketyr**
made during Gr8Conf Hackergarten with great support of @jlstrater and @Faradax

### CODE REVIEW

**Comment by musketyr** [comment]
I'm not quite sure what's happening, I got following when I try to run the test locally:

```
objc[45110]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/java (0x10e8dc4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10f8ef4e0). One of the two will be used. Which one is undefined.

Assertion failed: 

assert result.output.contains('CodeNarc rule violations were found')
       |      |      |
       |      |      false
       |      :codenarcMain FAILED
       |       
       |      FAILURE: Build failed with an exception.
       |       
       |      * What went wrong:
       |      Execution failed for task ':codenarcMain'.
       |      > java.lang.ClassNotFoundException: org.codenarc.ant.CodeNarcTask
       |       
       |      * Try:
       |      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
       |       
       |      * Get more help at https://help.gradle.org
       |       
       |      BUILD FAILED in 8s
       |      1 actionable task: 1 executed
       org.gradle.testkit.runner.internal.FeatureCheckBuildResult@22fcf7ab


	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
	at org.codenarc.gradle.GradlePluginCompilationClasspathTest.testRunningEnhancedRulesFromGradleBuildOnCodeThatUsesAstTransformations(GradlePluginCompilationClasspathTest.groovy:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by erdi** [comment]
How are you running the test, Vladimir?

**Comment by musketyr** [comment]
from IntelliJ

**Comment by musketyr** [comment]
@chrismair thanks for the feedback! 

1) I would still prefer having the issue as `1` as this is an error which is not easy to spot and creates an (un)expected runtime exception but I've changed it in f300fd6183d74bf0e575729e4402a0fc72ebabf9

2) you can use `size` but the maximum size (=length of the String) is the important information which determines the size of the column in the database (including falling back to database defaults if the maximum size is missing)

3) please, see f300fd6183d74bf0e575729e4402a0fc72ebabf9 for updated description

4) I will add the tests next week, I'm currently at the spot with very bad connection (1MB/minute or so)

**Comment by chrismair** [comment]
The changes so far looks good. But you also need to update the test to reflect the new rule  priority of 2. Please run the full CodeNarc test suite before a commit.

**Comment by chrismair** [comment]
Thanks for the contribution!

**Pull request merged**
