### PR TITLE
Add MethodDeclarationNameTrailingWhitespace rule.

### PR DESCRIPTION
**Pull request by erdi**
PR for #584.

### CODE REVIEW

**Comment by erdi** [comment]
Merged `master` in to resolve conflicts and make it easier to accept and merge this PR.

**Comment by chrismair** [comment]
That rule name is unwieldy, but I cannot think of a better one. *Naming is hard!* Thanks for the contribution.

**Comment by chrismair** [comment]
I am wondering about the inconsistency of the name of this rule with the other `SpaceAfterNotOperator` rule, especially since this rule and `MethodCallNameTrailingWhitespace` are not really checking for "trailing" whitespace, but rather checking for space "in between", like `SpaceAfterNotOperator` does.

I am considering renaming these rules to `SpaceAfterMethodDeclarationName` and `SpaceAfterMethodCallName`. Any thoughts?

**Comment by erdi** [comment]
Yeah, _naming is hard_ especially when naming things in what is not your first language so I'm always happy to accept ideas from others when it comes to naming. I think that your suggestions of `SpaceAfterMethodDeclarationName` and `SpaceAfterMethodCallName` are a) better and b) more consistent with `SpaceAfterMethodCallName`.

Would you like me to provide a PR with renaming these rules or would you like to rename them yourself? Keep in mind that it might be a bit more than just simply renaming the rules and their classes - I might have used the word "trailing" in descriptions and documentation...

**Comment by chrismair** [comment]
If you are willing and able to provide a PR for the renaming of those two rules, that would be great. Thanks.

**Comment by erdi** [comment]
Sure thing, will do.

**Pull request merged**
