### PR TITLE
Using AST rule to check def usages

### PR DESCRIPTION
**Pull request by armsargis**

### CODE REVIEW

**Comment by armsargis** [comment]
build and test are passed locally and in travis also if you check logs test are passed also but for some reason its saying all checks ae failed

**Comment by jlstrater** [comment]
Passes for me as well.  None of the individual tests failed on the ci server. It looks like a temporary problem with Travis.  It should be able to be rerun by one of the admins on this project.

**Comment by armsargis** [comment]
I did a little bit refactoring and add more testes and squashed commits to make nice merge and test are passed as well

**Comment by chrismair** [comment]
Nice. Thanks for the contribution!

**Pull request merged**
