### PR TITLE
Method chaining indentation improvements

### PR DESCRIPTION
**Pull request by dmurat**
This PR implements https://github.com/CodeNarc/CodeNarc/issues/510

At the moment CodeNarc's IndentationRule supports the indentation checks for following two styles of chained methods:

```
// style 1
buildFileList().collect { item ->
            item.name
        }
        .each1 { name -> println name }
        .each2 { someName ->
            println someName
        }
        .each3 { name ->
            println name
        }

// style 2
buildFileList()
        .collect { item ->
            item.name
        }
        .each1 { name -> println name }
        .each2 { someName ->
            println someName
        }
        .each3 { name ->
            println name
        }

```

This PR adds support for additional style of chained methods indentation:
```
// style 3
buildFileList().collect { item ->
                   item.name
               }
               .each1 { name -> println name }
               .each2 { someName ->
                   println someName
               }
               .each3 { name ->
                   println name
               }
```

In addition, PR also improves the reporting of expected columns for chained method calls.

Tnx

### CODE REVIEW

**Comment by chrismair** [comment]
Nice work! A few requests:

 - Rename the test class to `IndentationRule_MethodChainingTest` to follow naming convention for other "extra" test classes. And change @author to you.
 - Provide brief textual description of style 1, 2, 3 (and examples if necessary) in the comments at the top of the test class. I am confused because style 2 and 3 seem reversed from how they are described in #510.
- Please locally test with Groovy 3 and make sure the two `IndentationRule` test classes run clean. That rule is especially problematic in Groovy 3. For instance, temporarily modify `build.gradle`:
```
        def groovyVersion = '3.0.4'
        //def groovyVersion = '2.5.12'
```

**Comment by dmurat** [comment]
Tnx. 

Yes, you are right. Styles references in PR and in #510 are different. In PR I started with what already exists in CodeNarc (style 1 and 2), and the added new supported style 3.

I've just run local tests with Groovy 3.0.5. `IndentationRuleTest` and `IndentationRule_MethodChainingTest` passes cleanly. However, `UnnecessarySemicolonRuleTest.test_Field()` fails. This is the only test (of 5267) that fails with Groovy 3.0.5.
As it seems unrelated, I didn't check the details. Is this ok?

**Comment by dmurat** [comment]
To make sure that my changes did not mess up something, as an additional check, I just run all tests against the `master` branch with Groovy 3.0.5. `UnnecessarySemicolonRuleTest.test_Field()` fails in that case too with the same failure output. So it really looks like it is not related to this PR.

**Comment by chrismair** [comment]
Thanks for the contribution! And thanks for doing the extra testing with Groovy 3. Yeah, supporting both Groovy 2.x and 3.x will be a bit of a pain for a while.

**Pull request merged**
