### PR TITLE
Added some consistency to getting dependency version

### PR DESCRIPTION
**Pull request by russellsanborn**
I added all dependency versions to the gradle.properties file.

### CODE REVIEW

**Comment by chrismair** [comment]
Thanks for the suggestion and work to implement it.

But I think that just makes the "build.gradle" harder to read/maintain. I am more inclined to move *groovyVersion* and *slf4jVersion* into **build.gradle**, as simple variables. I don't ever need to override those on the command-line, so they don't really need to be Gradle *properties*.

**Comment by russellsanborn** [comment]
Sounds good to me. I usually just put it in build.gradle too. I can update this PR for you or feel free to close it, Your call.

**Comment by russellsanborn** [comment]
Updated. Like I said, feel free to close this if it is not what you want. And thanks again for CodeNarc. I've been enjoying digging in and understanding how things work more.

**Comment by chrismair** [comment]
I will just make those values simple variables, I think, and only the ones used more than once. But thanks for the help.

**Pull request closed without merging**
