### PR TITLE
Add ImplicitClosureParameter rule.

### LINKED ISSUE #371: Rule for use of implicit closure parameters
Some developers want to avoid magic like the `it` variable, to reduce risk. Could we have a CodeNarc rule that encourages coders to use explicit closure variables?

http://groovy-lang.org/closures.html

### PR DESCRIPTION
**Pull request by erdi**
Fixes #371.

### CODE REVIEW

**Comment by chrismair** [comment]
Thanks for the contribution, Marcin.
1. Are the huge diffs with existing files because of line-endings? Can we avoid/revert that?
2. Add a test for no-arg closure with code, e.g. `{ println 123 }`.

**Comment by erdi** [comment]
Oh sorry, I wasn't aware that the line endings were changed. I will revert, of course. I will also add the test you asked for.

**Comment by erdi** [comment]
All that you've asked for should be there now, @chrismair.

**Comment by chrismair** [comment]
I have to admit, I would expect the behavior of this rule to be that `{ println 123 }` would not produce a violation, since it does not use `it`. That's what motivated me asking for that test to be added. Are you thinking there are teams out there that insist that `->` always be specified within all closures?

**Comment by erdi** [comment]
Yeah, you seem to have a point there. Pretty pointless to have a violation when you are actually not referencing `it`. And thinking that I only decided to submit a PR for this feature request cause it seemed like an easy one to implement. 🤣

**Comment by erdi** [comment]
So, how is it looking now?

**Comment by erdi** [comment]
So, how is it looking now?

**Comment by chrismair** [comment]
Nice. Thanks Marcin.

**Pull request merged**
