### PR TITLE
Add NoBlankLineBeforeAnnotatedField rule.

### PR DESCRIPTION
**Pull request by erdi**
PR for #582.

### CODE REVIEW

**Comment by erdi** [comment]
Merged `master` in to resolve conflicts and make it easier to accept and merge this PR.

**Comment by chrismair** [comment]
Can you add a test for a field that has multiple annotations across more than one line.

**Comment by erdi** [comment]
Sure thing, will do. 👍  I'm a bit busy at the moment but I should have time to do this on Sunday.

**Comment by erdi** [comment]
> Can you add a test for a field that has multiple annotations across more than one line.

This has now been done. I did not know which case you actually meant so I added a test for when there is a violation and one where there isn't for fields annotated in such way.

**Comment by chrismair** [comment]
Looks great. Thanks!

**Pull request merged**
