### PR TITLE
Enhance IndentationRule to take into account Label Indent

### PR DESCRIPTION
**Pull request by xmac11**
Fixes https://github.com/CodeNarc/CodeNarc/issues/712

### Description
Currently, the following syntax is considered as a violation of `IndentationRule`

```groovy
def "should be true"() {
    expect:
        1 == 1
```

This PR introduces a `indentUnderLabel` boolean property to make this configurable. 
The default value is `false` in order to be backwards compatible.
When it is set to `true`, then code within the label should be indented with the number of spaces defined by the `spacesPerIndentLevel` property.

Additionally, the following change is made in order to allow labels without a text description.

```diff
private static boolean isSpockBlockLabel(Statement statement) {
    return (statement.statementLabel in SPOCK_BLOCKS &&
            statement instanceof ExpressionStatement &&
-           statement.expression.class == ConstantExpression &&
-           statement.expression.type.clazz == String
    )
}
```

### How has this been tested
Unit test are added covering:
- No violations, including multiple nested blocks
- No violations for labels with and without a description
- Violations when `indentUnderLabel` property is not respected

### CODE REVIEW

**Comment by chrismair** [comment]
Nice contribution. I like it.

Would it be acceptable and sufficient to just have a boolean that controls whether the statements under a label should be indented a single level or not?

The existing rule configuration property is `spacesPerIndentLevel`, and the rest of the rule logic is concerned with the *indent level*. Could we have this new behavior align with that? I'm hoping it is not a requirement that the statements under a label be indented for some number of spaces other than `spacesPerIndentLevel`.

**Comment by xmac11** [comment]
Good point @chrismair, I was also wondering the same. 
The only reason I went with this approach is that Groovy Code Style exposes a separate property for `Label indent`.

Screenshot 2023-03-08 at 10 01 00 AM

But I suppose most users will be using the same number of spaces everywhere.
Please let me know what you prefer and I'll go with it.

**Comment by xmac11** [comment]
@chrismair done :)

**Comment by chrismair** [comment]
Looks good. Thanks for the contribution.

**Pull request merged**
