### PR TITLE
Allow to send JSON RuleSets as string arguments 

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
PR Ready, CI ok :) https://travis-ci.org/github/CodeNarc/CodeNarc/builds/726728885

**Comment by chrismair** [comment]
Good stuff.

 - Please remove the support for XML ruleset string. That is too much extra code and complexity for something I don't expect to ever be needed. I assume and hope that means you can totally get rid of `StringRuleSet`.
 - Revert formatting changes to `CodeNarcRunnerTest`, especially adding spaces after colon for map entries. That is not the predominant project code style.

**Comment by nvuillam** [comment]
@chrismair Updated, CI ok 👍  -> https://travis-ci.org/github/CodeNarc/CodeNarc/builds/726927813

About formatting in CodeNarcRunnerTest, the enforced rules are SpaceAfterOpeningBrace and SpaceBeforeClosingBrace

In all other files it doesn't seem to rewrite all code .... and you sure you want me to disable those rules ? The result could be less clean :/

**Comment by chrismair** [comment]
My comment about the formatting was about you adding spaces after the colon (before the opening brace), so the SpaceAfterOpeningBrace and SpaceBeforeClosingBrace should not apply. Is it perhaps enabling *SpaceAroundMapEntryColon*?

Other than that, the changes look fine.

**Comment by chrismair** [comment]
Thanks for the contribution!

**Comment by nvuillam** [comment]
Sorry I delayed the reformatting because auto-format in VsCode added the space you didn't want ... 

Thanks for having validated the PR anyway :)

**Pull request merged**
