### PR TITLE
CodeNarc: Implement a CLI for baseline usage.

### PR DESCRIPTION
**Pull request by UlrichEckhardt**
This complements the setting in the Ant task, where you can define a baseline. You specify the baseline using `-excludeBaseline=<FILENAME>`. It is aimed to solve #282.

This branch is based on v2.2.0, even though the commit cleanly applies to master as well. The problem is that I can't get the tests to work there, even without my changes. Still, this is something to try out and review.

### CODE REVIEW

**Comment by chrismair** [comment]
From my initial review, this looks like the right approach. Updating the associated doc in "codenarc-command-line.md" would also be appreciated. Thanks.

**Comment by UlrichEckhardt** [comment]
Just updated the pull request, found some other places, too.

Just a side question: The instructions in docker/README.md, they pull a specific version of CodeNarc from GitHub and build an image from that, right? Is there a way to create one from the local sources?

**Comment by UlrichEckhardt** [comment]
## Docker Image Build

Okay, managed to build a Docker image functioning equivalently to the the one from dockerhub:
```Dockerfile
#### Build Image
FROM gradle:6.9-jdk11-alpine AS gradle

WORKDIR /gradle
COPY . .
RUN gradle --quiet --no-daemon shadowJar

#### Runtime Image
FROM openjdk:11-jre-slim

COPY --from=gradle /gradle/build/libs/CodeNarc-2.2.0-all.jar /lib/codenarc-all.jar
RUN chmod 555 /lib/codenarc-all.jar

WORKDIR /ws

ENTRYPOINT ["java", "-jar", "/lib/codenarc-all.jar"]
```

## Pull Request

Using the Docker image, I was able to verify that creating and using baseline files works from the commandline, making this pull request ready for review. I ran the tests using Gradle inside of a Docker container as well, but that already worked before.

## Future Ideas

From using other linters with baselines, I can say that there are a few things missing to make this really useful:
 * Fail on unexpected error: When encountering any error not in the baseline, the linter should signal an error. Yes, you can use the three `-maxPriority*Violations=0` options, but that's cumbersome and not very elegant.
 * Fail on unexpected success: When not encountering an error that is in the baseline, the linter should signal an error as well. This forces the use to regenerate the baseline and/or manually edit it. However, it prevents the error from being re-introduced with a second change.
 * Timestamp: I wonder if it's necessary to include it (`timestamp="Mar 10, 2022, 7:12:12 PM"`) in the baseline, even more so since it's using a localized, timezone-dependent format. This simply makes builds (and linting is a kind-of build) non-repeatable. More practically, I couldn't implement the above "fail on missing error" feature myself by just running CodeNarc and comparing with the previous results, because every run differs.

**Comment by chrismair** [comment]
Thanks for the contribution!

**Comment by chrismair** [comment]
And thanks for going through the extra work required to test it properly.

**Comment by UlrichEckhardt** [comment]
Thank you for your work as well, Chris! Do you have any release plans? I actually have a case where I want to use this feature in a Jenkins pipeline and I would rather not use an unreleased version there.

**Comment by chrismair** [comment]
I'm targeting a release within the next several days.

**Pull request merged**
