### PR TITLE
Ends with blank line before closing brace rule

### PR DESCRIPTION
**Pull request by tarkil**
Check the location of the closing brace of a class. By default, enforce that there must be a blank line before the closing class brace, except if the class is empty and is written in a single line. A blank line is defined as any line that does not contain any visible characters.

### CODE REVIEW

**Comment by chrismair** [comment]
Thanks for the contribution!

Good idea. I expect we may want a corresponding rule re: classes beginning with a blank line; some teams may have that as a standard as well.

Some requested changes:
1. Move the class to the formatting package and the rule to the formatting ruleset. 
2. Rename to **ClassEndsWithBlankLine**. 
3. Rename *singleLineClassesAllowed* to *ignoreSingleLineClasses*.
4. Rename *blankLineBeforeClosingBrace* property -- perhaps *blankLineRequired*? 
5. Remove “final” modifier from method parameters; that is not conventional in this codebase. 
6. Add @SuppressWarnings(‘TrailingWhitespace’) to `ClassEndsWithBlankLineBeforeClosingBraceRequiredRuleTest` instead of explicitly configuring the **TrailingWhitespace** rule in `RunCodeNarcAgainstProjectSourceCode.ruleset`.
7. Back out unnecessary changes to `RunCodeNarcAgainstProjectSourceCode.properties`? 

Tests: 
1. Add remaining properties to `testRuleProperties()`. 
2. Remove `// given:` and `// expect:` comments -- it is not wrong or bad, but is unconventional in this codebase.
3.  Please adjust formatting for multi-line `assertViolations()` so that it is one violation per line. 
4. Adjust test names to reflect renamed rule and properties (above).

**Comment by erdi** [comment]
+1 on requesting changes that will make the contribution more aligned with
the conventions of the codebase (namely point 5 in requested changes and
point 2 in tests).

**Comment by tarkil** [comment]
I have applied tour suggestions:

1.   _Move the class to the formatting package and the rule to the formatting ruleset_. Done
2. _Rename to ClassEndsWithBlankLine._ Done
3.   _Rename singleLineClassesAllowed to ignoreSingleLineClasses._ Done
4. _Rename blankLineBeforeClosingBrace property -- perhaps blankLineRequired?_ I accept your suggestion. Done
5. _Remove “final” modifier from method parameters; that is not conventional in this codebase._ Ok
6. _Add @SuppressWarnings(‘TrailingWhitespace’) to ClassEndsWithBlankLineBeforeClosingBraceRequiredRuleTest instead of explicitly configuring the TrailingWhitespace rule in RunCodeNarcAgainstProjectSourceCode.ruleset._ I did not know that I can use this annotation. I have disabled this rule only for the SOURCE variables, in order to avoid trailing white spaces in the rest of the file.
7. _Back out unnecessary changes to RunCodeNarcAgainstProjectSourceCode.properties?_ Done
8.  _Add remaining properties to testRuleProperties()._ Done
9.  _Remove // given: and // expect: comments -- it is not wrong or bad, but is unconventional in this codebase._ Ok
10. _Please adjust formatting for multi-line assertViolations() so that it is one violation per line._ Done
11. _Adjust test names to reflect renamed rule and properties (above)._ Done

**Comment by chrismair** [comment]
Thanks for the changes. A few more requests...

 - Change rule description in CHANGELOG, codenarc-base-messages.properties and class javadoc. I think the description “Check the location of the closing brace of a class.” -- misplaces the focus on the brace, rather than the blank line at the end of the class. How about something like “Check whether the class ends with a blank line.”.

 - **codenarc-rules-formatting.apt**: 
       - Should be <Since CodeNarc 1.3>. 
       - We don’t need the config properties described in both the \<ul\> and in the table -- remove \<ul\> above the table.

 - **ClassEndsWithBlankLineRuleTest**: 
        - Remove `static skipTestThatUnrelatedCodeHasNoViolations`.
        - Remove @SuppressWarnings('TrailingWhitespace' from each test; make it a class level annotation. If that doesn’t work, then we will have to move it back to disabling it in the rule configuration. 
        - Rename *WhenClassEndsWithBlankLineIsRequired()  test names to *WhenBlankLineIsRequired(); likewise for *IsNotRequired methods.

**Comment by tarkil** [comment]
I have updated rule description in CHANGELOG, codenarc-base-messages.properties, codenarc-rules-formatting.apt and class javadoc. Besides, I have also set version 1.3 in codenarc-rules-formatting.apt and CHANGELOG. 

On the other hand, I have removed @SuppressWarnings and renamed test methods

**Comment by chrismair** [comment]
Great. Thanks for the contribution!

**Pull request merged**
